pipeline {
  agent {
    docker {
      image 'node:alpine3.12'
    }
  }

  stages {
    stage('Verify') {
      steps {
        sh'''
          node --version
          npm --version
        '''
        sh 'printenv'
        sh 'ls -l "${WORKSPACE}"'
      }
    }
    stage('Build') {
      steps {
        dir("${WORKSPACE}/02/solution") {
          sh'''
            npm install
            npm run build
          '''
        }
      }
    }
    stage('Unit tests') {
      steps {
        dir("${WORKSPACE}/02/solution") {
          sh'npm test'
        }
      }
    }
  }
}
