pipeline {
  agent any

  environment {
    RELEASE='0.0.1'
  }

  stages {
    stage("Build") {
      agent any // Se puede usar otro agent como docker
      environment {
        LOG_LEVEL='INFO'
      }
      steps {
        echo "Building release ${RELEASE} with log level $LOG_LEVEL"
      }
    }

    stage("Test") {
      steps {
        echo "Testing release ${RELEASE} with log level $LOG_LEVEL"
      }
    }
  }
}
