// library identifier: '<repository-name>@<branch>'

library identifier: 'jenkins-library@main',
        retriever: modernSCM([$class: 'GitSCMSource', remote: 'https://github.com/Nasdan/jenkins-library.git'])

pipeline {
  agent any

  stages {
    stage('Audit tools') {
      steps {
        auditTools2(message: "This is demo 2")
      }
    }
  }
}
