pipeline {
  agent any

  environment {
    RELEASE='0.0.1'
  }

  stages {
    stage("Build") {
      agent any // Se puede usar otro agent como docker
      environment {
        LOG_LEVEL='INFO'
      }
      parallel {
        stage('Linux') {
          steps {
            echo "Release #${RELEASE} for ${STAGE_NAME}"
          }
        }
        stage('Windows') {
          steps {
            echo "Release #${RELEASE} for ${STAGE_NAME}"
          }
        }
      }
    }

    stage("Test") {
      steps {
        echo "Testing release ${RELEASE}"
      }
    }

    stage("Deploy") {
      input {
        message 'Deploy?'
        ok 'Do it!'
        parameters {
          string(name: 'TARGET_ENVIRONMENt', defaultValue: 'PROD', description: 'Target deployment environment')
        }
      }
      steps {
        echo "Deploying release ${RELEASE} to env ${TARGET_ENVIRONMENT}"
      }
    }
  }

  post {
    always {
      echo "Deploy DONE!"
    }
  }
}
